const Items=[
{  id: 1,
   name: "Neymar Jr", 
   AGE: 33, 
   team: "Al-Hilal",
   country:"Brazil",
   continent:"South America"},
{
    id: 2,
    name: "Eden Hazard", 
    AGE: 34, 
    team: "Retired",
    country:"Belguim",
    continent:"Europe", 
},
{
    id: 3,
    name: "Cole Palmer", 
    AGE: 22, 
    team: "Chelsea",
    country:"England",
    continent:"Europe", 
},
{
    id: 4,
    name: "Kobbie Mainoo", 
    AGE: 18, 
    team: "Manchester United",
    country:"England",
    continent:"Europe", 
},
{
   id: 5,
   name: "Mohammed Salah", 
   AGE: 32, 
   team: "Liverpool",
   country:"Egypt",
   continent:"Africa", 
},
{
    id: 6,
   name: "Mohammed Kudus", 
   AGE: 24, 
   team: "Westham United",
   country:"Ghana",
   continent:"Africa", 
},
{
    id: 7,
   name: "Moreira Savio", 
   AGE: 19, 
   team: "Manchester City",
   country:"Brazil",
   continent:"South America", 
},
{
    id: 8,
   name: "Thiago Silva",
   AGE: 39,  
   team: "Fluminese",
   country:"Brazil",
   continent:"South America", 
},
{
   id: 9,
   name: "Moises Caicedo", 
   AGE: 22, 
   team: "Chelsea",
   country:"Ecuador",
   trophies:0,
   continent:"South America", 
},
{
    id: 10,
   name: "Marcus Rashford", 
   AGE: 28, 
   team: "Manchester Utd",
   country:"England",
   continent:"Europe", 
},
{
    id: 11,
   name: "Cristiano Ronaldo", 
   AGE: 38, 
   team: "Al-Nassr",
   country:"Portugal",
   continent:"Europe", 
},
{
    id: 12,
   name: "Leo Messi", 
   AGE: 36, 
   team: "Inter Miami",
   country:"Argentina",
   continent:"South America", 
},
{
    id: 13,
   name: "Eduardo Camaviga", 
   AGE: 24, 
   team: "Real Madrid",
   country:"France",
   continent:"Europe", 
},
{
    id: 14,
   name: "Jadon Sancho", 
   AGE: 26, 
   team: "Borussia Dortmund",
   country:"England",
   continent:"Europe", 
},
{
    id: 15,
   name: "Florian Wirtz", 
   AGE: 23, 
   team: "Bayer Leverkusen",
   country:"Germany",
   continent:"Europe", 
},
{
    id: 16,
   name: "Bukayo Saka", 
   AGE: 23, 
   team: "Arsenal",
   country:"England",
   continent:"Europe", 
},
{
    id: 17,
    name: "Victor Boniface", 
    AGE: 22, 
    team: "Bayer Leverkusen",
    country:"Nigeria",
    continent:"Africa", 
 },
 {
    id: 18,
    name: "David Alaba", 
    AGE: 32, 
    team: "Real madrid",
    country:"Austria",
    continent:"Europe", 
 },
 {
    id: 19,
    name: "Sofyi Amrabat", 
    AGE: 33, 
    team: "Manchester United",
    country:"Morocco",
    continent:"Africa", 
 },
 {
    id: 20,
    name: "Stanley Nwabali", 
    AGE: 26, 
    team: "Chippa United",
    country:"Nigeria",
    continent:"Africa", 
 },

]

export default Items;